const state={token:"",data:null,action:null};const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function toast(message,error=false){const node=$("toast");node.textContent=message;node.className=error?"show error":"show";clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.className="",4000)}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body?.error?.message||`HTTP ${response.status}`);return body}
async function boot(){try{const status=await api("/api/v1/status");$("runtime").textContent=`服务在线 · ${status.version}`;$("auth").showModal()}catch(error){$("runtime").textContent="服务异常";toast(error.message,true)}}
$("authForm").addEventListener("submit",async event=>{event.preventDefault();state.token=$("adminToken").value;try{await load();$("auth").close();$("adminToken").value="";toast("已进入授权中心")}catch(error){state.token="";toast(error.message,true)}});$("lock").addEventListener("click",()=>{state.token="";$("auth").showModal()});
async function load(){state.data=await api("/api/v1/admin/data");["customers","activation_codes","devices","licenses"].forEach(key=>{if(!Array.isArray(state.data[key]))state.data[key]=[]});render()}
function customerName(id){return state.data.customers.find(item=>item.id===id)?.name||id}
function render(){const data=state.data;$("customerCount").textContent=data.customers.length;$("codeCount").textContent=data.activation_codes.length;$("deviceCount").textContent=data.devices.length;$("licenseCount").textContent=data.licenses.length;$("codeCustomer").innerHTML=data.customers.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join("");$("licenseRows").innerHTML=data.licenses.length?data.licenses.slice().reverse().map(item=>`<tr><td><strong>${esc(customerName(item.customer_id))}</strong><br><small>${esc(item.edition)}</small></td><td><code>${esc(item.id)}</code></td><td><small>${esc(item.device_id)}</small></td><td>${item.max_users}</td><td>${item.expires_at?new Date(item.expires_at).toLocaleDateString():"永久"}</td><td><span class="status ${item.revoked?"revoked":""}">${item.revoked?"已吊销":"有效"}</span></td><td><div class="actions">${item.revoked?"":`<button data-action="renew" data-id="${esc(item.id)}">续期</button><button data-action="migrate" data-id="${esc(item.id)}">迁移</button><button class="revoke" data-action="revoke" data-id="${esc(item.id)}">吊销</button>`}</div></td></tr>`).join(""):`<tr><td colspan="7">尚无授权</td></tr>`;$("codeRows").innerHTML=data.activation_codes.length?data.activation_codes.slice().reverse().map(item=>`<tr><td>${esc(customerName(item.customer_id))}</td><td><code>•••• ${esc(item.code_hint)}</code></td><td>${esc(item.edition)}</td><td>${item.max_users} 人</td><td>${item.activations}/${item.max_activations}</td><td><span class="status ${item.enabled?"":"revoked"}">${item.enabled?"可用":"停用"}</span></td></tr>`).join(""):`<tr><td colspan="6">尚无激活码</td></tr>`}
$("customerForm").addEventListener("submit",async event=>{event.preventDefault();try{await api("/api/v1/admin/customers",{method:"POST",body:JSON.stringify({name:$("customerName").value,contact:$("customerContact").value})});event.target.reset();await load();toast("客户已创建")}catch(error){toast(error.message,true)}});
$("codeForm").addEventListener("submit",async event=>{event.preventDefault();try{const result=await api("/api/v1/admin/activation-codes",{method:"POST",body:JSON.stringify({customer_id:$("codeCustomer").value,edition:$("edition").value,max_users:Number($("maxUsers").value),valid_days:Number($("validDays").value),max_activations:Number($("maxActivations").value),features:$("features").value.split(",").map(v=>v.trim()).filter(Boolean)})});$("newCode").textContent=result.activation_code;$("reveal").classList.remove("hidden");await load();toast("激活码已生成，请立即保存")}catch(error){toast(error.message,true)}});
$("copyCode").addEventListener("click",async()=>{await navigator.clipboard.writeText($("newCode").textContent);toast("激活码已复制")});$("refresh").addEventListener("click",async()=>{try{await load();toast("授权台账已刷新")}catch(error){toast(error.message,true)}});
$("licenseRows").addEventListener("click",event=>{const button=event.target.closest("button[data-action]");if(!button)return;const kind=button.dataset.action;state.action={kind,id:button.dataset.id};if(kind==="revoke"){runAction("");return}$("actionTitle").textContent=kind==="renew"?"续期 License":"迁移到新设备";$("actionLabel").firstChild.textContent=kind==="renew"?"续期天数":"新设备指纹";$("actionValue").type=kind==="renew"?"number":"text";$("actionValue").value=kind==="renew"?"365":"";$("actionDialog").showModal()});
$("actionForm").addEventListener("submit",async event=>{event.preventDefault();await runAction($("actionValue").value);$("actionDialog").close()});async function runAction(value){const {kind,id}=state.action;const path=`/api/v1/admin/licenses/${encodeURIComponent(id)}/${kind}`;const body=kind==="renew"?{days:Number(value)}:kind==="migrate"?{device_id:value}:{};try{await api(path,{method:"POST",body:JSON.stringify(body)});await load();toast(kind==="renew"?"License 已续期":kind==="migrate"?"License 已迁移":"License 已吊销")}catch(error){toast(error.message,true)}}
boot();
